#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "usage: pcl2pdf INPUT.pcl OUTPUT.pdf"
  exit 1
fi

gs_image="michaelneu/ghostpcl"

docker run \
  --rm \
  -it \
  -v `pwd`:/gs \
  -w /gs \
  $gs_image \
    -sDEVICE=pdfwrite \
    -sOutputFile=$2 \
    $1
